on:
  push:
    branches:
      - master
name: Build Gatsby
jobs:
  build_gatsby:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: deploy
        uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.API_KEY }}
          deploy-branch: gh-pages
          skip-publish: false
          GATSBY_USERNAME: ${{ secrets.USERNAME }}
          GATSBY_PASSWORD: ${{ secrets.PASSWORD }}
          GATSBY_CHANNEL: ${{ secrets.CHANNEL }}
